# This is a basic workflow to help you get started with Actions

name: test_all_conf

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the test_build branch
  push:
    branches:    
      - '*test_all'
  pull_request:
    branches:    
      - '*test_all'


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive      
        
      - name: Pull docker image
        run: docker pull paparazziuav/pprz-ci

      - name: run test
        run: |
          export useX=false
          export MAKEFLAGS=-j$(nproc)
          $GITHUB_WORKSPACE/docker/run.sh paparazziuav/pprz-ci make test_all_conf

